services:
  smart_living:
    container_name: smart_living
    pull_policy: build
    build:
      context: .
      args:
        - SERVER_HOST=${SERVER_HOST}
    image: smart_living:latest
    environment:
      SERVER_HOST: http://supermicro-shutdown:8000
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
