services:
  smart_living:
    container_name: smart_living
    build:
      context: .
      args:
        - SERVER_HOST=${SERVER_HOST}
    image: smart_living:latest
    pull_policy: build
    environment:
      SERVER_HOST: http://192.168.1.118:8001
    networks:
      - nginx-proxy-manager_default
    restart: unless-stopped

networks:
  nginx-proxy-manager_default:
    external: true
