version: '3.8'

services:
  smart_living:
    container_name: smart_living
    build:
      context: .
      args:
        - SERVER_HOST=${SERVER_HOST}
    image: smart_living:latest
    environment:
      SERVER_HOST: http://supermicro-shutdown:8000
    networks:
      - nginx_proxy_manager_overlay
    restart: unless-stopped

networks:
  nginx_proxy_manager_overlay:
    external: true
